DEFAULT_APPS = [
    {
        "id": "effect-png",
        "name": "3D微缩模型转换器",
        "description": "微缩模型",
        "webapp_id": "2014608238859259906",
        "node_id": "3",
        "field_name": "image",
        "input_type": "image",
        "output_type": "png",
        "auto_unzip": False,
        "category": "3D化",
        "favorite": True,
        "accent": "#8fb1ff",
        "cover_path": "",
        "source_url": "https://www.runninghub.cn/ai-detail/2014608238859259906",
        "prompt_node_id": "",
        "prompt_field_name": "",
        "default_prompt": "",
        "sort_order": 10,
        "enabled": True,
    },
    {
        "id": "private-zip",
        "name": "高级换装",
        "description": "人物换装",
        "webapp_id": "2054095300863774721",
        "node_id": "191",
        "field_name": "image",
        "input_type": "image",
        "output_type": "zip",
        "auto_unzip": True,
        "category": "换装",
        "favorite": True,
        "accent": "#8a5cf6",
        "cover_path": "",
        "source_url": "https://www.runninghub.cn/ai-detail/2054095300863774721",
        "prompt_node_id": "",
        "prompt_field_name": "",
        "default_prompt": "",
        "sort_order": 20,
        "enabled": True,
    },
]
